[project]
name = "git-aicommit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "gitpython>=3.1.45",
    "langchain-core>=1.0.5",
    "langchain-ollama>=1.0.0",
    "poml>=0.0.8",
    "pydantic>=2.12.4",
]
